Repository ICT-FUNney/WalletClient, pull requests merged in 2019-08, with the labels that each got.

#39 fix: send画面で発生していた頻繁にactionが起こる問題，及び入力のバリデーションを作成
  src/components/Send.js
Labels: B, good first issue

#37 style: ヘッダー及びフッターを美しくした
  public/index.css
  public/index.html
  src/components/Footer.js
  src/components/Header.js
Labels: good first issue

#38 feat: connectionの状態を管理するStoreの追加
  src/actions/Connecting.js
  src/components/Send.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/reducers/Connecting.js
  src/reducers/index.js
  src/sagas/Funney.js
  src/sagas/Send.js
  src/sagas/SignIn.js
Labels: good first issue

#36 feat: tokenに対応した形にしました
  src/actions/Send.js
  src/actions/User.js
  src/apis/Funney.js
  src/apis/Send.js
  src/apis/SignIn.js
  src/apis/User.js
  src/components/App.js
  src/components/Send.js
  src/components/Settings.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/reducers/User.js
  src/reducers/index.js
  src/sagas/Funney.js
  src/sagas/Send.js
  src/sagas/User.js
  src/sagas/index.js
Labels: A, enhancement, good first issue

#35 feat: QRコード生成機能の追加
  public/index.css
  public/manifest.json
  src/components/App.js
  src/components/Footer.js
  src/components/Request.js
  src/components/Send.js
  src/helpers/GetQueryParam.js
  src/sagas/User.js
Labels: A, enhancement

#40 feat:取引中のFUNneyの表示
  src/components/Home.js
  src/reducers/Funney.js
  src/sagas/Funney.js
Labels: A, enhancement, good first issue
